# syntax=docker/dockerfile:1.7-labs
# Stage 1: Build the application
# FROM node:20.18.1-slim AS builder

# RUN apt-get update && apt-get install -y build-essential python3

# RUN mkdir /usr/src/app
# WORKDIR /usr/src/app
# RUN npm install -g bun
# RUN npm install -g lerna@7.4.2
# ENV PATH=/usr/src/app/node_modules/.bin:$PATH

# # Do an initial install and then a final install
# COPY package.json yarn.lock preinstall.js lerna.json ./
# COPY --parents ./addOns/package.json ./addOns/*/*/package.json ./extensions/*/package.json ./modes/*/package.json ./platform/*/package.json ./

# RUN bun pm cache rm
# RUN bun install

# # ADD CUSTOM EXTENSIONS
# RUN yarn run cli link-extension ./custom-extensions/curved-mpr-extension

# # Copy the local directory
# COPY --link --exclude=yarn.lock --exclude=package.json --exclude=Dockerfile . .

# # Build here
# # After install it should hopefully be stable until the local directory changes
# ENV QUICK_BUILD true
# # ENV GENERATE_SOURCEMAP=false
# ARG APP_CONFIG=config/docker-nginx-dcm4chee.js
# ARG PUBLIC_URL=/
# ENV PUBLIC_URL=${PUBLIC_URL}



# RUN bun run show:config
# RUN bun run build

# # Precompress files
# RUN chmod u+x .docker/compressDist.sh
# RUN ./.docker/compressDist.sh
# Stage 1: build
FROM node:20.18.1-slim AS builder

RUN apt-get update && apt-get install -y build-essential python3
WORKDIR /usr/src/app

RUN npm install -g lerna@7.4.2
ENV PATH=/usr/src/app/node_modules/.bin:$PATH

COPY package.json yarn.lock lerna.json preinstall.js ./
COPY --parents ./addOns/package.json ./addOns/*/*/package.json ./extensions/*/package.json ./modes/*/package.json ./platform/*/package.json ./
COPY platform/cli/package.json ./platform/cli/package.json
COPY custom-extensions/curved-mpr-extension/package.json ./custom-extensions/curved-mpr-extension/package.json
COPY modes/longitudinal/package.json ./modes/longitudinal/package.json

# Теперь Yarn видит все workspace до установки
RUN yarn config set workspaces-experimental true
RUN yarn install

# После установки — копируем остальной код
COPY . .

ENV QUICK_BUILD true
# ENV GENERATE_SOURCEMAP=false
ARG APP_CONFIG=config/docker-nginx-dcm4chee.js
ARG PUBLIC_URL=/
ENV PUBLIC_URL=${PUBLIC_URL}


# Ссылкуем расширение через CLI и собираем
RUN yarn run cli link-extension ./custom-extensions/curved-mpr-extension
RUN yarn run build

# # Stage 3: Bundle the built application into a Docker container
# # which runs Nginx using Alpine Linux
# FROM nginxinc/nginx-unprivileged:1.27-alpine AS final
# #RUN apk add --no-cache bash
# ARG PUBLIC_URL=/
# ENV PUBLIC_URL=${PUBLIC_URL}
# ARG PORT=80
# ENV PORT=${PORT}
# RUN rm /etc/nginx/conf.d/default.conf
# USER nginx
# COPY --chown=nginx:nginx .docker/Viewer-v3.x /usr/src
# RUN chmod 777 /usr/src/entrypoint.sh
# COPY --from=builder /usr/src/app/platform/app/dist /usr/share/nginx/html${PUBLIC_URL}
# # Copy paths that are renamed/redirected generally
# # Microscopy libraries depend on root level include, so must be copied
# COPY --from=builder /usr/src/app/platform/app/dist/dicom-microscopy-viewer /usr/share/nginx/html/dicom-microscopy-viewer

# # In entrypoint.sh, app-config.js might be overwritten, so chmod it to be writeable.
# # The nginx user cannot chmod it, so change to root.
# USER root
# RUN chown -R nginx:nginx /usr/share/nginx/html
# USER nginx
# ENTRYPOINT ["/usr/src/entrypoint.sh"]
# CMD ["nginx", "-g", "daemon off;"]
# # Stage 2: Bundle the built application into a Docker container which runs NGINX using Alpine Linux
FROM nginx:alpine

# # Create directories for logs and html content if they don't already exist
RUN mkdir -p /var/log/nginx /var/www/html


# # Copy build output to serve static files
COPY --from=builder /usr/src/app/platform/app/dist /var/www/html

# # Expose HTTP and HTTPS ports
EXPOSE 80 443

# # Start NGINX
CMD ["nginx", "-g", "daemon off;"]
