# syntax=docker/dockerfile:1.7-labs

# Stage 1: build
FROM node:20.18.1-slim AS builder

RUN apt-get update && apt-get install -y build-essential python3

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g bun
RUN npm install -g lerna@7.4.2
ENV PATH=/usr/src/app/node_modules/.bin:$PATH

COPY package.json yarn.lock lerna.json preinstall.js ./
COPY --parents ./addOns/package.json ./addOns/*/*/package.json ./extensions/*/package.json ./modes/*/package.json ./platform/*/package.json ./
COPY platform/cli/package.json ./platform/cli/package.json
COPY custom-extensions/curved-mpr-extension/package.json ./custom-extensions/curved-mpr-extension/package.json
COPY modes/longitudinal/package.json ./modes/longitudinal/package.json

RUN yarn config set workspaces-experimental true
RUN yarn install

COPY . .

ENV QUICK_BUILD true
# ENV GENERATE_SOURCEMAP=false
ARG APP_CONFIG=config/docker-nginx-dcm4chee.js
ARG PUBLIC_URL=/
ENV PUBLIC_URL=${PUBLIC_URL}

RUN yarn run cli link-extension ./custom-extensions/curved-mpr-extension
RUN yarn run build


# # Stage 2: Bundle the built application into a Docker container which runs NGINX using Alpine Linux
FROM nginx:alpine

# # Create directories for logs and html content if they don't already exist
RUN mkdir -p /var/log/nginx /var/www/html


# # Copy build output to serve static files
COPY --from=builder /usr/src/app/platform/app/dist /var/www/html

# # Expose HTTP and HTTPS ports
EXPOSE 80 443

# # Start NGINX
CMD ["nginx", "-g", "daemon off;"]
